services:
  backend:
    image: incidental/backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "5000:5000"
      - "8888:8888"
    volumes:
      - ".:/srv"
    env_file:
      - .env
    command: uvicorn app.main:app --port 5000 --host 0.0.0.0 --reload

  worker:
    image: incidental/backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ".:/srv"
    env_file:
      - .env
    command: celery -A app.worker worker --loglevel=info

  postgres:
    image: postgres:16
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend
    ports:
      - "5432:5432"

  redis:
    image: redis:7

  beat:
    image: incidental/backend:latest
    depends_on:
      - postgres
    volumes:
      - ".:/srv"
    env_file:
      - .env
    command: celery -A app.worker beat --loglevel=INFO -s /var/run/celerybeat

volumes:
  postgresdata:
    driver: local
