export enum IncidentRoleKind {
  REPORTER = 'REPORTER',
  LEAD = 'LEAD'
}

export enum IncidentStatusCategory {
  TRIAGE = 'TRIAGE',
  ACTIVE = 'ACTIVE',
  POST_INCIDENT = 'POST_INCIDENT',
  CLOSED = 'CLOSED'
}

export enum FormType {
  CREATE_INCIDENT = 'CREATE_INCIDENT',
  UPDATE_INCIDENT = 'UPDATE_INCIDENT',
  ACCEPT_INCIDENT = 'ACCEPT_INCIDENT'
}

export enum OrganisationKind {
  DEFAULT = 'default',
  SLACK = 'slack'
}

export enum FieldKind {
  INCIDENT_TYPE = 'INCIDENT_TYPE',
  INCIDENT_SEVERITY = 'INCIDENT_SEVERITY',
  INCIDENT_STATUS = 'INCIDENT_STATUS',
  INCIDENT_NAME = 'INCIDENT_NAME',
  INCIDENT_INITIAL_STATUS = 'INCIDENT_INITIAL_STATUS',
  INCIDENT_SUMMARY = 'INCIDENT_SUMMARY',
  USER_DEFINED = 'USER_DEFINED'
}

export enum FieldInterfaceKind {
  SINGLE_SELECT = 'SINGLE_SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  TEXT = 'TEXT',
  TEXTAREA = 'TEXTAREA'
}

export enum MemberRole {
  MEMBER = 'MEMBER'
}

export enum RequirementType {
  REQUIRED = 'REQUIRED',
  OPTIONAL = 'OPTIONAL',
  CONDITIONAL = 'CONDITIONAL'
}

export enum StatusPageKind {
  PUBLIC = 'PUBLIC',
  CUSTOMER = 'CUSTOMER',
  INTERNAL = 'INTERNAL'
}
