"""make slack fields optional

Revision ID: 91a050e23239
Revises: ca73b4793d1a
Create Date: 2024-05-17 16:44:46.183162

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91a050e23239"
down_revision: Union[str, None] = "ca73b4793d1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("incident", "slack_channel_id", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("incident", "slack_channel_name", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("incident", "slack_channel_name", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("incident", "slack_channel_id", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
