"""add field

Revision ID: 12eff6845f01
Revises: 3acb7e527ecf
Create Date: 2024-06-04 21:56:39.101537

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision: str = "12eff6845f01"
down_revision: Union[str, None] = "3acb7e527ecf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("timestamp", sa.Column("can_delete", sa.Boolean(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("timestamp", "can_delete")
    # ### end Alembic commands ###
