"""announcements

Revision ID: c7df5642fbb2
Revises: f81d4417b5bc
Create Date: 2024-02-04 22:14:51.157731

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c7df5642fbb2"
down_revision: Union[str, None] = "f81d4417b5bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcement",
        sa.Column("organisation_id", sa.String(length=50), nullable=False),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisation.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_announcement_organisation_id"), "announcement", ["organisation_id"], unique=False)
    op.create_table(
        "slack_message",
        sa.Column("organisation_id", sa.String(length=50), nullable=False),
        sa.Column("announcement_id", sa.String(length=50), nullable=False),
        sa.Column("slack_message_id", sa.UnicodeText(), nullable=False),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["announcement_id"], ["announcement.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisation.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_slack_message_announcement_id"), "slack_message", ["announcement_id"], unique=False)
    op.create_index(op.f("ix_slack_message_organisation_id"), "slack_message", ["organisation_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_slack_message_organisation_id"), table_name="slack_message")
    op.drop_index(op.f("ix_slack_message_announcement_id"), table_name="slack_message")
    op.drop_table("slack_message")
    op.drop_index(op.f("ix_announcement_organisation_id"), table_name="announcement")
    op.drop_table("announcement")
    # ### end Alembic commands ###
