"""add ux to incident field value

Revision ID: 402e20f380c0
Revises: 5a9c42082ac1
Create Date: 2024-07-22 08:34:25.540538

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "402e20f380c0"
down_revision: Union[str, None] = "5a9c42082ac1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "field", "is_system", existing_type=sa.BOOLEAN(), nullable=False, existing_server_default=sa.text("false")
    )
    op.create_unique_constraint(None, "incident_field_value", ["incident_id", "field_id"])
    op.drop_column("incident_field_value", "value_textarea")
    op.alter_column(
        "incident_type",
        "is_editable",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "incident_type",
        "is_deletable",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "incident_type",
        "is_deletable",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "incident_type",
        "is_editable",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.add_column("incident_field_value", sa.Column("value_textarea", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "incident_field_value", type_="unique")
    op.alter_column(
        "field", "is_system", existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text("false")
    )
    # ### end Alembic commands ###
