"""add job table

Revision ID: ca73b4793d1a
Revises: 7ea94dc22604
Create Date: 2024-05-16 21:34:46.010549

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ca73b4793d1a"
down_revision: Union[str, None] = "7ea94dc22604"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("name", sa.UnicodeText(), nullable=False),
        sa.Column("exception", sa.UnicodeText(), nullable=True),
        sa.Column("is_retryable", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("queue", sa.UnicodeText(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "PROCESSED", "ERROR", name="jobstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("processing_at", sa.DateTime(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("errored_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job")
    # ### end Alembic commands ###
