"""rename field

Revision ID: 811b69c66d49
Revises: 29efd1d2c977
Create Date: 2024-03-09 13:10:13.061612

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "811b69c66d49"
down_revision: Union[str, None] = "29efd1d2c977"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("form_field", "can_remove", new_column_name="is_deletable")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("form_field", "is_deletable", new_column_name="can_remove")
    # ### end Alembic commands ###
