"""update form field types

Revision ID: 1e16307da3cd
Revises: c7df5642fbb2
Create Date: 2024-02-11 18:08:22.711578

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e16307da3cd"
down_revision: Union[str, None] = "c7df5642fbb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "form_field",
        "kind",
        existing_type=sa.VARCHAR(length=13),
        type_=sa.Enum(
            "SINGLE_SELECT",
            "MULTI_SELECT",
            "TEXT",
            "TEXTAREA",
            "INCIDENT_TYPE",
            "SEVERITY_TYPE",
            "INCIDENT_STATUS",
            name="formfieldkind",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "form_field",
        "kind",
        existing_type=sa.Enum(
            "SINGLE_SELECT",
            "MULTI_SELECT",
            "TEXT",
            "TEXTAREA",
            "INCIDENT_TYPE",
            "SEVERITY_TYPE",
            "INCIDENT_STATUS",
            name="formfieldkind",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=13),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
