"""add uniq for role name and reference

Revision ID: 7e5d07b95d98
Revises: cf938c4d09fd
Create Date: 2024-07-03 21:10:41.890704

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e5d07b95d98"
down_revision: Union[str, None] = "cf938c4d09fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uix_incident_role_org_name", "incident_role", ["organisation_id", "name"])
    op.create_unique_constraint(
        "uix_incident_role_org_slack_reference", "incident_role", ["organisation_id", "slack_reference"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_incident_role_org_slack_reference", "incident_role", type_="unique")
    op.drop_constraint("uix_incident_role_org_name", "incident_role", type_="unique")
    # ### end Alembic commands ###
