"""add description to timestamps

Revision ID: b40753c385bc
Revises: 12eff6845f01
Create Date: 2024-06-07 22:45:04.561591

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b40753c385bc"
down_revision: Union[str, None] = "12eff6845f01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("timestamp", sa.Column("description", sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("timestamp", "description")
    # ### end Alembic commands ###
