"""add fields to form field

Revision ID: a39e48a59d78
Revises: 1e16307da3cd
Create Date: 2024-02-12 22:37:55.796228

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a39e48a59d78"
down_revision: Union[str, None] = "1e16307da3cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_field", sa.Column("label", sa.UnicodeText(), nullable=False))
    op.add_column("form_field", sa.Column("can_remove", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_field", "can_remove")
    op.drop_column("form_field", "label")
    # ### end Alembic commands ###
