"""add lifecycle

Revision ID: 2c714795f8fe
Revises: 3e7d09e28b97
Create Date: 2024-07-28 10:29:11.351691

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c714795f8fe"
down_revision: Union[str, None] = "3e7d09e28b97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lifecycle",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("organisation_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.UnicodeText(), nullable=False),
        sa.Column("is_triage_available", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_deletable", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisation.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lifecycle_organisation_id"), "lifecycle", ["organisation_id"], unique=False)
    # ### end Alembic commands ###
    op.alter_column("incident_status", "sort_order", new_column_name="rank")
    op.alter_column("field", "kind", type_=sa.VARCHAR(24))


def downgrade() -> None:
    op.alter_column("incident_status", "rank", new_column_name="sort_order")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lifecycle_organisation_id"), table_name="lifecycle")
    op.drop_table("lifecycle")
    # ### end Alembic commands ###
