"""add status update

Revision ID: 900cd353b79c
Revises: a39e48a59d78
Create Date: 2024-02-13 20:34:46.950974

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "900cd353b79c"
down_revision: Union[str, None] = "a39e48a59d78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident_update",
        sa.Column("incident_id", sa.String(length=50), nullable=False),
        sa.Column("creator_id", sa.String(length=50), nullable=False),
        sa.Column("summary", sa.UnicodeText(), nullable=True),
        sa.Column("new_incident_status_id", sa.String(length=50), nullable=True),
        sa.Column("new_incident_severity_id", sa.String(length=50), nullable=True),
        sa.Column("previous_incident_status_id", sa.String(length=50), nullable=True),
        sa.Column("previous_incident_severity_id", sa.String(length=50), nullable=True),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["creator_id"], ["user.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["incident_id"], ["incident.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["new_incident_severity_id"], ["incident_severity.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["new_incident_status_id"], ["incident_status.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["previous_incident_severity_id"], ["incident_severity.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["previous_incident_status_id"], ["incident_status.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incident_update_creator_id"), "incident_update", ["creator_id"], unique=False)
    op.create_index(op.f("ix_incident_update_incident_id"), "incident_update", ["incident_id"], unique=False)
    op.create_index(
        op.f("ix_incident_update_new_incident_severity_id"),
        "incident_update",
        ["new_incident_severity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_update_new_incident_status_id"),
        "incident_update",
        ["new_incident_status_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_update_previous_incident_severity_id"),
        "incident_update",
        ["previous_incident_severity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_update_previous_incident_status_id"),
        "incident_update",
        ["previous_incident_status_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_incident_update_previous_incident_status_id"), table_name="incident_update")
    op.drop_index(op.f("ix_incident_update_previous_incident_severity_id"), table_name="incident_update")
    op.drop_index(op.f("ix_incident_update_new_incident_status_id"), table_name="incident_update")
    op.drop_index(op.f("ix_incident_update_new_incident_severity_id"), table_name="incident_update")
    op.drop_index(op.f("ix_incident_update_incident_id"), table_name="incident_update")
    op.drop_index(op.f("ix_incident_update_creator_id"), table_name="incident_update")
    op.drop_table("incident_update")
    # ### end Alembic commands ###
