"""status page schema

Revision ID: 73a48304d62c
Revises: e83f1525f07e
Create Date: 2024-10-30 20:44:46.735817

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73a48304d62c"
down_revision: Union[str, None] = "e83f1525f07e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "status_page",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("organisation_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.UnicodeText(), nullable=False),
        sa.Column("page_type", sa.Enum("PUBLIC", "CUSTOMER", "INTERNAL", name="statuspagekind"), nullable=False),
        sa.Column("custom_domain", sa.String(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("public_url", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisation.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="ux_status_page_slug"),
    )
    op.create_index(op.f("ix_status_page_organisation_id"), "status_page", ["organisation_id"], unique=False)
    op.create_table(
        "component",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("status_page_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("is_uptime_shown", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["status_page_id"], ["status_page.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_component_status_page_id"), "component", ["status_page_id"], unique=False)
    op.create_table(
        "status_page_incident",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("status_page_id", sa.String(length=50), nullable=False),
        sa.Column("creator_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(["status_page_id"], ["status_page.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_status_page_incident_creator_id"), "status_page_incident", ["creator_id"], unique=False)
    op.create_index(
        op.f("ix_status_page_incident_status_page_id"), "status_page_incident", ["status_page_id"], unique=False
    )
    op.create_table(
        "component_affected",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("status_page_incident_id", sa.String(), nullable=False),
        sa.Column("component_id", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPERATIONAL", "DEGRADED_PERFORMANCE", "PARTIAL_OUTAGE", "FULL_OUTAGE", name="componentstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["component.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_page_incident_id"],
            ["status_page_incident.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_component_affected_component_id"), "component_affected", ["component_id"], unique=False)
    op.create_index(
        op.f("ix_component_affected_status_page_incident_id"),
        "component_affected",
        ["status_page_incident_id"],
        unique=False,
    )
    op.create_table(
        "component_event",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("status_page_incident_id", sa.String(length=50), nullable=False),
        sa.Column("component_id", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPERATIONAL", "DEGRADED_PERFORMANCE", "PARTIAL_OUTAGE", "FULL_OUTAGE", name="componentstatus"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["component.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_page_incident_id"],
            ["status_page_incident.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_component_event_component_id"), "component_event", ["component_id"], unique=False)
    op.create_index(
        op.f("ix_component_event_status_page_incident_id"), "component_event", ["status_page_incident_id"], unique=False
    )
    op.create_table(
        "status_page_incident_update",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("status_page_incident_id", sa.String(length=50), nullable=False),
        sa.Column("creator_id", sa.String(length=50), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("INVESTIGATING", "IDENTIFIED", "MONITORING", "RESOLVED", name="statuspageincidentstatus"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_page_incident_id"],
            ["status_page_incident.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_status_page_incident_update_creator_id"), "status_page_incident_update", ["creator_id"], unique=False
    )
    op.create_index(
        op.f("ix_status_page_incident_update_status_page_incident_id"),
        "status_page_incident_update",
        ["status_page_incident_id"],
        unique=False,
    )
    op.create_table(
        "status_page_item",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("parent_id", sa.String(length=50), nullable=True),
        sa.Column("status_page_id", sa.String(length=50), nullable=False),
        sa.Column("component_id", sa.String(length=50), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["component.id"],
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["status_page_item.id"], ondelete="set null"),
        sa.ForeignKeyConstraint(["status_page_id"], ["status_page.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_status_page_item_parent_id"), "status_page_item", ["parent_id"], unique=False)
    op.create_index(op.f("ix_status_page_item_status_page_id"), "status_page_item", ["status_page_id"], unique=False)
    op.create_table(
        "component_update",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("status_page_incident_update_id", sa.String(), nullable=False),
        sa.Column("component_id", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPERATIONAL", "DEGRADED_PERFORMANCE", "PARTIAL_OUTAGE", "FULL_OUTAGE", name="componentstatus"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["component.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_page_incident_update_id"],
            ["status_page_incident_update.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_component_update_component_id"), "component_update", ["component_id"], unique=False)
    op.create_index(
        op.f("ix_component_update_status_page_incident_update_id"),
        "component_update",
        ["status_page_incident_update_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_component_update_status_page_incident_update_id"), table_name="component_update")
    op.drop_index(op.f("ix_component_update_component_id"), table_name="component_update")
    op.drop_table("component_update")
    op.drop_index(op.f("ix_status_page_item_status_page_id"), table_name="status_page_item")
    op.drop_index(op.f("ix_status_page_item_parent_id"), table_name="status_page_item")
    op.drop_table("status_page_item")
    op.drop_index(
        op.f("ix_status_page_incident_update_status_page_incident_id"), table_name="status_page_incident_update"
    )
    op.drop_index(op.f("ix_status_page_incident_update_creator_id"), table_name="status_page_incident_update")
    op.drop_table("status_page_incident_update")
    op.drop_index(op.f("ix_component_event_status_page_incident_id"), table_name="component_event")
    op.drop_index(op.f("ix_component_event_component_id"), table_name="component_event")
    op.drop_table("component_event")
    op.drop_index(op.f("ix_component_affected_status_page_incident_id"), table_name="component_affected")
    op.drop_index(op.f("ix_component_affected_component_id"), table_name="component_affected")
    op.drop_table("component_affected")
    op.drop_index(op.f("ix_status_page_incident_status_page_id"), table_name="status_page_incident")
    op.drop_index(op.f("ix_status_page_incident_creator_id"), table_name="status_page_incident")
    op.drop_table("status_page_incident")
    op.drop_index(op.f("ix_component_status_page_id"), table_name="component")
    op.drop_table("component")
    op.drop_index(op.f("ix_status_page_organisation_id"), table_name="status_page")
    op.drop_table("status_page")
    # ### end Alembic commands ###

    op.execute("drop TYPE componentstatus")
    op.execute("drop type statuspageincidentstatus")
    op.execute("drop type statuspagekind")
