"""add multi default value

Revision ID: e83f1525f07e
Revises: 8c69704046a5
Create Date: 2024-09-11 20:53:08.899428

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e83f1525f07e"
down_revision: Union[str, None] = "8c69704046a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_field", sa.Column("default_value_multi", postgresql.JSONB(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_field", "default_value_multi")
    # ### end Alembic commands ###
