"""rename col

Revision ID: 121421196cb8
Revises: 79fd21991098
Create Date: 2024-02-02 21:05:08.187292

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "121421196cb8"
down_revision: Union[str, None] = "79fd21991098"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("incident_severity", "position", new_column_name="rating")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("incident_severity", "rating", new_column_name="position")
    # ### end Alembic commands ###
