"""invites

Revision ID: 3a0d4e196a08
Revises: 724f3167ea80
Create Date: 2024-12-14 20:51:38.524116

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a0d4e196a08"
down_revision: Union[str, None] = "724f3167ea80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invite",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("organisation_id", sa.String(length=50), nullable=False),
        sa.Column("inviter_id", sa.String(length=50), nullable=False),
        sa.Column("invitee_id", sa.String(length=50), nullable=True),
        sa.Column("email_address", sa.UnicodeText(), nullable=False),
        sa.Column("role", sa.Enum("MEMBER", name="memberrole", native_enum=False), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["invitee_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inviter_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invite_invitee_id"), "invite", ["invitee_id"], unique=False)
    op.create_index(op.f("ix_invite_inviter_id"), "invite", ["inviter_id"], unique=False)
    op.create_index(op.f("ix_invite_organisation_id"), "invite", ["organisation_id"], unique=False)
    op.alter_column(
        "organisation_member",
        "role",
        existing_type=sa.TEXT(),
        type_=sa.Enum("MEMBER", name="memberrole", native_enum=False),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organisation_member",
        "role",
        existing_type=sa.Enum("MEMBER", name="memberrole", native_enum=False),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_invite_organisation_id"), table_name="invite")
    op.drop_index(op.f("ix_invite_inviter_id"), table_name="invite")
    op.drop_index(op.f("ix_invite_invitee_id"), table_name="invite")
    op.drop_table("invite")
    # ### end Alembic commands ###
