"""create role assignments

Revision ID: f81d4417b5bc
Revises: 121421196cb8
Create Date: 2024-02-03 23:56:51.707885

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f81d4417b5bc"
down_revision: Union[str, None] = "121421196cb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident_role",
        sa.Column("organisation_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.UnicodeText(), nullable=False),
        sa.Column("description", sa.UnicodeText(), nullable=False),
        sa.Column("guide", sa.UnicodeText(), nullable=True),
        sa.Column("slack_reference", sa.UnicodeText(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("REPORTER", "LEAD", "CUSTOM", name="incidentrolekind", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisation.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incident_role_organisation_id"), "incident_role", ["organisation_id"], unique=False)
    op.create_table(
        "incident_role_assignment",
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("incident_id", sa.String(length=50), nullable=False),
        sa.Column("incident_role_id", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["incident_id"], ["incident.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["incident_role_id"], ["incident_role.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "incident_id", "incident_role_id", name="ux_user_incident_role"),
    )
    op.alter_column(
        "incident_status",
        "category",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum(
            "TRIAGE",
            "ACTIVE",
            "POST_INCIDENT",
            "CLOSED",
            name="incidentstatuscategoryenum",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "incident_status",
        "category",
        existing_type=sa.Enum(
            "TRIAGE",
            "ACTIVE",
            "POST_INCIDENT",
            "CLOSED",
            name="incidentstatuscategoryenum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_table("incident_role_assignment")
    op.drop_index(op.f("ix_incident_role_organisation_id"), table_name="incident_role")
    op.drop_table("incident_role")
    # ### end Alembic commands ###
