"""add settings

Revision ID: 2db1cdb35211
Revises: deef44a368e5
Create Date: 2024-01-31 21:33:20.892584

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2db1cdb35211"
down_revision: Union[str, None] = "deef44a368e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("organisation_id", sa.String(length=50), nullable=False),
        sa.Column("slack_channel_name_format", sa.UnicodeText(), nullable=False),
        sa.Column("incident_reference_format", sa.UnicodeText(), nullable=False),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisation.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_settings_organisation_id"), "settings", ["organisation_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_settings_organisation_id"), table_name="settings")
    op.drop_table("settings")
    # ### end Alembic commands ###
