"""add default to incident type

Revision ID: 3e7d09e28b97
Revises: 3c885bcaa883
Create Date: 2024-07-26 21:45:52.430021

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e7d09e28b97"
down_revision: Union[str, None] = "3c885bcaa883"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident_type", sa.Column("is_default", sa.Boolean(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident_type", "is_default")
    # ### end Alembic commands ###
