"""status page urls

Revision ID: e4af2032001a
Revises: 3a0d4e196a08
Create Date: 2024-12-24 23:08:31.473386

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4af2032001a"
down_revision: Union[str, None] = "3a0d4e196a08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("status_page", sa.Column("support_url", sa.String(), nullable=True))
    op.add_column("status_page", sa.Column("support_label", sa.String(), nullable=False, server_default="Support"))
    op.add_column("status_page", sa.Column("privacy_policy_url", sa.String(), nullable=True))
    op.add_column("status_page", sa.Column("terms_of_service_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("status_page", "terms_of_service_url")
    op.drop_column("status_page", "privacy_policy_url")
    op.drop_column("status_page", "support_url")
    op.drop_column("status_page", "support_label")
    # ### end Alembic commands ###
