"""fields to incident type

Revision ID: 5a9c42082ac1
Revises: 25a10d717000
Create Date: 2024-07-16 20:14:27.957004

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a9c42082ac1"
down_revision: Union[str, None] = "25a10d717000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident_type_field",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("incident_type_id", sa.String(length=50), nullable=False),
        sa.Column("field_id", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["field_id"], ["field.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["incident_type_id"], ["incident_type.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incident_type_field_field_id"), "incident_type_field", ["field_id"], unique=False)
    op.create_index(
        op.f("ix_incident_type_field_incident_type_id"), "incident_type_field", ["incident_type_id"], unique=False
    )
    # ### end Alembic commands ###
    op.add_column("incident_type", sa.Column("is_deletable", sa.Boolean, server_default="0"))
    op.add_column("incident_type", sa.Column("is_editable", sa.Boolean, server_default="0"))
    op.add_column("field", sa.Column("is_system", sa.Boolean, server_default="false"))


def downgrade() -> None:
    op.drop_column("field", "is_system")
    op.drop_column("incident_type", "is_editable")
    op.drop_column("incident_type", "is_deletable")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_incident_type_field_incident_type_id"), table_name="incident_type_field")
    op.drop_index(op.f("ix_incident_type_field_field_id"), table_name="incident_type_field")
    op.drop_table("incident_type_field")
    # ### end Alembic commands ###
