"""add description to incident

Revision ID: 4ab0568af723
Revises: 900cd353b79c
Create Date: 2024-02-18 19:02:11.306648

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ab0568af723"
down_revision: Union[str, None] = "900cd353b79c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident", sa.Column("description", sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident", "description")
    # ### end Alembic commands ###
