"""add annoucment

Revision ID: 79fd21991098
Revises: 2db1cdb35211
Create Date: 2024-02-01 21:44:48.990118

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79fd21991098"
down_revision: Union[str, None] = "2db1cdb35211"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("settings", sa.Column("slack_announcement_channel_id", sa.UnicodeText(), nullable=True))
    op.add_column("settings", sa.Column("slack_announcement_channel_name", sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "slack_announcement_channel_name")
    op.drop_column("settings", "slack_announcement_channel_id")
    # ### end Alembic commands ###
