import type { Metadata } from "next";

import "@/styles/reset.css";
import "@/styles/index.css";
import "@/styles/variables.css";

import StyledComponentsRegistry from "@/lib/registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
