name: Run frontend tests

on:
  pull_request:
    branches: [main]
    paths:
      - frontend/**
      - .github/workflows/pr-frontend.yml

jobs:
  build:
    defaults:
      run:
        working-directory: frontend

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: "frontend/.nvmrc"

      - name: Install deps
        run: |
          npm install -g pnpm
          pnpm install
      - name: Run tests
        run: |
          pnpm vitest run
        env:
          VITE_API_BASE_URL: https://api.incidental.dev

      - name: Build check
        run: |
          pnpm run build